# Exported from Render on 2024-07-24T10:53:40Z
services:
- type: web
  name: miniproject
  runtime: python
  repo: https://github.com/Nehajillala/miniproject
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn Stock-RL.py
version: "1"
